CREATE DATABASE inventory;

CREATE TABLE items(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  added_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);